application: uplus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /media/img
  static_dir: static/images
  expiration: 1d

- url: /cron.*
  script: cron.app
  login: admin

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
